### ISSUE TITLE
CNF: EnumUtils

### ISSUE THREAD

**Issue by tmcgrath** [aws-samples/clickstream-producer-for-apache-kafka#12]
After cloning and building a jar, attempting to run with:

`java $EXTRA_ARGS -jar KafkaClickstreamClient-1.0-SNAPSHOT.jar -t ExampleTopic -pfp /tmp/kafka/producer.properties_msk -nt 8 -rf 10800 -nle -gsr -gsrr $region -gar -gcs $schema_compatibility > /tmp/producer.log 2>&1 &`

which results in error

```
KafkaClientEC2Instance1 [ec2-user@ip-10-0-1-199 explode$ cat /tmp/producer.log 
[2022-01-20 00:06:47,493] (com.amazonaws.kafka.samples.KafkaClickstreamClient) - INFO Start time: 7157978 
 
Exception in thread "main" java.lang.NoClassDefFoundError: software/amazon/awssdk/utils/internal/EnumUtils
        at software.amazon.awssdk.services.glue.model.Compatibility.<clinit>(Compatibility.java:42)
        at com.amazonaws.kafka.samples.KafkaProducerFactory.createProducer(KafkaProducerFactory.java:115)
        at com.amazonaws.kafka.samples.KafkaClickstreamClient.runProducer(KafkaClickstreamClient.java:141)
        at com.amazonaws.kafka.samples.KafkaClickstreamClient.main(KafkaClickstreamClient.java:227)
Caused by: java.lang.ClassNotFoundException: software.amazon.awssdk.utils.internal.EnumUtils
```

**Comment by tmcgrath** [comment]
I found a workaround, but I haven't tested enough to submit a PR

If I update the POM to

```
        <dependency>
            <groupId>software.amazon.glue</groupId>
            <artifactId>schema-registry-serde</artifactId>
            <version>1.1.8</version>
    </dependency>
    <dependency>
                <groupId>software.amazon.awssdk</groupId>
                    <artifactId>utils</artifactId>
                        <version>2.17.113</version>
                </dependency>
```

and rebuild, I can run. 

I'm not sure if the bump to 1.1.8 of `software.amazon.glue` is necessary or not, but the addition of `software.amazon.awssdk` definitely was required for the workaround.

**Comment by tmcgrath** [comment]
Same issue of ClassNotFound EnumUtils is also found in https://github.com/aws-samples/clickstream-producer-for-apache-kafka btw

**Comment by awsalialem** [comment]
I tried the bump to 1.1.8 of `software.amazon.glue ` but received same error. 
I fixed this issue locally by updating the pom to:

```
 <dependency>
            <groupId>software.amazon.glue</groupId>
            <artifactId>schema-registry-serde</artifactId>
            <version>1.1.5</version>
        </dependency>

        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>glue</artifactId>
            <version>2.17.52</version>
        </dependency>
```
I have tested the above change and works for here as well as [https://github.com/aws-samples/clickstream-producer-for-apache-kafka](https://github.com/aws-samples/clickstream-producer-for-apache-kafka)
